gui:
  # nerdFontsVersion: "3"
  branchColorPatterns:
    'issue\d+': '#FF5D00'
    'fix\d+': '#00FF00'
    'feat\d+': '#FFFFFF'
  theme:
    activeBorderColor:
      - '#cdd6f4'
      - bold
    inactiveBorderColor:
      - '#585b70'
    optionsTextColor:
      - '#FF7A7A'
      - bold
    selectedLineBgColor:
      - '#542E2E'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#FF8400'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
